# Default values for nwdaf-netapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

analytics-info:
  enabled: true
  replicaCount: 1
  image:
    repository: dockerhub.mobilesandbox.cloud:9443/tactile5g/analytics_info
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.0.2"

data-management:
  enabled: true

events-subscription:
  enabled: true
  replicaCount: 0
  image:
    repository: dockerhub.mobilesandbox.cloud:9443/tactile5g/events_subs
    pullPolicy: Always
    # Overrides the image tag whose default is the chart appVersion.
    tag: "0.0.2"

ml-model-provisioning:
  enabled: true

mongo:
  enabled: false

mongo-express:
  enabled: true
  replicaCount: 1

nginx:
  enabled: true
