# Default values for nwdaf-netapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

analytics-info:
  enabled: true
  replicaCount: 1

data-management:
  enabled: true

events-subscription:
  enabled: true
  replicaCount: 1

ml-model-provisioning:
  enabled: true

mongo:
  enabled: true

mongo-express:
  enabled: true

nginx:
  enabled: true
