# Default values for nwdaf-netapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

analytics_info:
  enabled: true

data_management:
  enabled: true

events_subscription:
  enabled: false

ml_model_provisioning:
  enabled: false

mongo:
  enabled: false

mongo-express:
  enabled: false

nginx:
  enabled: false
