# Default values for nwdaf-netapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

analytics_info:
  enabled: true
  replicaCount: 0

data_management:
  enabled: true

events_subscription:
  enabled: true
  replicaCount: 0

ml_model_provisioning:
  enabled: true

mongo:
  enabled: true

mongo-express:
  enabled: true

nginx:
  enabled: true
