apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    {{- include "mongo.labels" . | nindent 8 }}
  name: mongo-pvc
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.storage }}