apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
   user nginx;
   
   events{
       worker_connections  1024;
   }
   
   http{
       server{
           listen 80;
           server_name localhost;
   
           location /nnwdaf-eventssubscription{
               proxy_pass      {{ .Values.configMap.uriEventSubscription }};
           }
   
           location /nnwdaf-datamanagement{
               proxy_pass     {{ .Values.configMap.uriDataManagement }};
           }
   
           location /nnwdaf-mlmodelprovision{
               proxy_pass      {{ .Values.configMap.uriMlModelProvisioning }};
           }
   
           location /nnwdaf-analyticsinfo{
               proxy_pass      {{ .Values.configMap.uriAnalyticsInfo }};
           }
       }
   }

