# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.collocated_nf_type import CollocatedNfType
from openapi_server import util

from openapi_server.models.collocated_nf_type import CollocatedNfType  # noqa: E501

class CollocatedNfInstance(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, nf_instance_id=None, nf_type=None):  # noqa: E501
        """CollocatedNfInstance - a model defined in OpenAPI

        :param nf_instance_id: The nf_instance_id of this CollocatedNfInstance.  # noqa: E501
        :type nf_instance_id: str
        :param nf_type: The nf_type of this CollocatedNfInstance.  # noqa: E501
        :type nf_type: CollocatedNfType
        """
        self.openapi_types = {
            'nf_instance_id': str,
            'nf_type': CollocatedNfType
        }

        self.attribute_map = {
            'nf_instance_id': 'nfInstanceId',
            'nf_type': 'nfType'
        }

        self._nf_instance_id = nf_instance_id
        self._nf_type = nf_type

    @classmethod
    def from_dict(cls, dikt) -> 'CollocatedNfInstance':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CollocatedNfInstance of this CollocatedNfInstance.  # noqa: E501
        :rtype: CollocatedNfInstance
        """
        return util.deserialize_model(dikt, cls)

    @property
    def nf_instance_id(self):
        """Gets the nf_instance_id of this CollocatedNfInstance.

        String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.    # noqa: E501

        :return: The nf_instance_id of this CollocatedNfInstance.
        :rtype: str
        """
        return self._nf_instance_id

    @nf_instance_id.setter
    def nf_instance_id(self, nf_instance_id):
        """Sets the nf_instance_id of this CollocatedNfInstance.

        String uniquely identifying a NF instance. The format of the NF Instance ID shall be a  Universally Unique Identifier (UUID) version 4, as described in IETF RFC 4122.    # noqa: E501

        :param nf_instance_id: The nf_instance_id of this CollocatedNfInstance.
        :type nf_instance_id: str
        """
        if nf_instance_id is None:
            raise ValueError("Invalid value for `nf_instance_id`, must not be `None`")  # noqa: E501

        self._nf_instance_id = nf_instance_id

    @property
    def nf_type(self):
        """Gets the nf_type of this CollocatedNfInstance.


        :return: The nf_type of this CollocatedNfInstance.
        :rtype: CollocatedNfType
        """
        return self._nf_type

    @nf_type.setter
    def nf_type(self, nf_type):
        """Sets the nf_type of this CollocatedNfInstance.


        :param nf_type: The nf_type of this CollocatedNfInstance.
        :type nf_type: CollocatedNfType
        """
        if nf_type is None:
            raise ValueError("Invalid value for `nf_type`, must not be `None`")  # noqa: E501

        self._nf_type = nf_type
