# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class NumberAverage(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, number=None, variance=None, skewness=None):  # noqa: E501
        """NumberAverage - a model defined in OpenAPI

        :param number: The number of this NumberAverage.  # noqa: E501
        :type number: float
        :param variance: The variance of this NumberAverage.  # noqa: E501
        :type variance: float
        :param skewness: The skewness of this NumberAverage.  # noqa: E501
        :type skewness: float
        """
        self.openapi_types = {
            'number': float,
            'variance': float,
            'skewness': float
        }

        self.attribute_map = {
            'number': 'number',
            'variance': 'variance',
            'skewness': 'skewness'
        }

        self._number = number
        self._variance = variance
        self._skewness = skewness

    @classmethod
    def from_dict(cls, dikt) -> 'NumberAverage':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The NumberAverage of this NumberAverage.  # noqa: E501
        :rtype: NumberAverage
        """
        return util.deserialize_model(dikt, cls)

    @property
    def number(self):
        """Gets the number of this NumberAverage.

        string with format 'float' as defined in OpenAPI.  # noqa: E501

        :return: The number of this NumberAverage.
        :rtype: float
        """
        return self._number

    @number.setter
    def number(self, number):
        """Sets the number of this NumberAverage.

        string with format 'float' as defined in OpenAPI.  # noqa: E501

        :param number: The number of this NumberAverage.
        :type number: float
        """
        if number is None:
            raise ValueError("Invalid value for `number`, must not be `None`")  # noqa: E501

        self._number = number

    @property
    def variance(self):
        """Gets the variance of this NumberAverage.

        string with format 'float' as defined in OpenAPI.  # noqa: E501

        :return: The variance of this NumberAverage.
        :rtype: float
        """
        return self._variance

    @variance.setter
    def variance(self, variance):
        """Sets the variance of this NumberAverage.

        string with format 'float' as defined in OpenAPI.  # noqa: E501

        :param variance: The variance of this NumberAverage.
        :type variance: float
        """
        if variance is None:
            raise ValueError("Invalid value for `variance`, must not be `None`")  # noqa: E501

        self._variance = variance

    @property
    def skewness(self):
        """Gets the skewness of this NumberAverage.

        string with format 'float' as defined in OpenAPI.  # noqa: E501

        :return: The skewness of this NumberAverage.
        :rtype: float
        """
        return self._skewness

    @skewness.setter
    def skewness(self, skewness):
        """Sets the skewness of this NumberAverage.

        string with format 'float' as defined in OpenAPI.  # noqa: E501

        :param skewness: The skewness of this NumberAverage.
        :type skewness: float
        """

        self._skewness = skewness
