# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class ProSeCapability(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, prose_direct_discovey=False, prose_direct_communication=False, prose_l2_ueto_network_relay=False, prose_l3_ueto_network_relay=False, prose_l2_remote_ue=False, prose_l3_remote_ue=False):  # noqa: E501
        """ProSeCapability - a model defined in OpenAPI

        :param prose_direct_discovey: The prose_direct_discovey of this ProSeCapability.  # noqa: E501
        :type prose_direct_discovey: bool
        :param prose_direct_communication: The prose_direct_communication of this ProSeCapability.  # noqa: E501
        :type prose_direct_communication: bool
        :param prose_l2_ueto_network_relay: The prose_l2_ueto_network_relay of this ProSeCapability.  # noqa: E501
        :type prose_l2_ueto_network_relay: bool
        :param prose_l3_ueto_network_relay: The prose_l3_ueto_network_relay of this ProSeCapability.  # noqa: E501
        :type prose_l3_ueto_network_relay: bool
        :param prose_l2_remote_ue: The prose_l2_remote_ue of this ProSeCapability.  # noqa: E501
        :type prose_l2_remote_ue: bool
        :param prose_l3_remote_ue: The prose_l3_remote_ue of this ProSeCapability.  # noqa: E501
        :type prose_l3_remote_ue: bool
        """
        self.openapi_types = {
            'prose_direct_discovey': bool,
            'prose_direct_communication': bool,
            'prose_l2_ueto_network_relay': bool,
            'prose_l3_ueto_network_relay': bool,
            'prose_l2_remote_ue': bool,
            'prose_l3_remote_ue': bool
        }

        self.attribute_map = {
            'prose_direct_discovey': 'proseDirectDiscovey',
            'prose_direct_communication': 'proseDirectCommunication',
            'prose_l2_ueto_network_relay': 'proseL2UetoNetworkRelay',
            'prose_l3_ueto_network_relay': 'proseL3UetoNetworkRelay',
            'prose_l2_remote_ue': 'proseL2RemoteUe',
            'prose_l3_remote_ue': 'proseL3RemoteUe'
        }

        self._prose_direct_discovey = prose_direct_discovey
        self._prose_direct_communication = prose_direct_communication
        self._prose_l2_ueto_network_relay = prose_l2_ueto_network_relay
        self._prose_l3_ueto_network_relay = prose_l3_ueto_network_relay
        self._prose_l2_remote_ue = prose_l2_remote_ue
        self._prose_l3_remote_ue = prose_l3_remote_ue

    @classmethod
    def from_dict(cls, dikt) -> 'ProSeCapability':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ProSeCapability of this ProSeCapability.  # noqa: E501
        :rtype: ProSeCapability
        """
        return util.deserialize_model(dikt, cls)

    @property
    def prose_direct_discovey(self):
        """Gets the prose_direct_discovey of this ProSeCapability.


        :return: The prose_direct_discovey of this ProSeCapability.
        :rtype: bool
        """
        return self._prose_direct_discovey

    @prose_direct_discovey.setter
    def prose_direct_discovey(self, prose_direct_discovey):
        """Sets the prose_direct_discovey of this ProSeCapability.


        :param prose_direct_discovey: The prose_direct_discovey of this ProSeCapability.
        :type prose_direct_discovey: bool
        """

        self._prose_direct_discovey = prose_direct_discovey

    @property
    def prose_direct_communication(self):
        """Gets the prose_direct_communication of this ProSeCapability.


        :return: The prose_direct_communication of this ProSeCapability.
        :rtype: bool
        """
        return self._prose_direct_communication

    @prose_direct_communication.setter
    def prose_direct_communication(self, prose_direct_communication):
        """Sets the prose_direct_communication of this ProSeCapability.


        :param prose_direct_communication: The prose_direct_communication of this ProSeCapability.
        :type prose_direct_communication: bool
        """

        self._prose_direct_communication = prose_direct_communication

    @property
    def prose_l2_ueto_network_relay(self):
        """Gets the prose_l2_ueto_network_relay of this ProSeCapability.


        :return: The prose_l2_ueto_network_relay of this ProSeCapability.
        :rtype: bool
        """
        return self._prose_l2_ueto_network_relay

    @prose_l2_ueto_network_relay.setter
    def prose_l2_ueto_network_relay(self, prose_l2_ueto_network_relay):
        """Sets the prose_l2_ueto_network_relay of this ProSeCapability.


        :param prose_l2_ueto_network_relay: The prose_l2_ueto_network_relay of this ProSeCapability.
        :type prose_l2_ueto_network_relay: bool
        """

        self._prose_l2_ueto_network_relay = prose_l2_ueto_network_relay

    @property
    def prose_l3_ueto_network_relay(self):
        """Gets the prose_l3_ueto_network_relay of this ProSeCapability.


        :return: The prose_l3_ueto_network_relay of this ProSeCapability.
        :rtype: bool
        """
        return self._prose_l3_ueto_network_relay

    @prose_l3_ueto_network_relay.setter
    def prose_l3_ueto_network_relay(self, prose_l3_ueto_network_relay):
        """Sets the prose_l3_ueto_network_relay of this ProSeCapability.


        :param prose_l3_ueto_network_relay: The prose_l3_ueto_network_relay of this ProSeCapability.
        :type prose_l3_ueto_network_relay: bool
        """

        self._prose_l3_ueto_network_relay = prose_l3_ueto_network_relay

    @property
    def prose_l2_remote_ue(self):
        """Gets the prose_l2_remote_ue of this ProSeCapability.


        :return: The prose_l2_remote_ue of this ProSeCapability.
        :rtype: bool
        """
        return self._prose_l2_remote_ue

    @prose_l2_remote_ue.setter
    def prose_l2_remote_ue(self, prose_l2_remote_ue):
        """Sets the prose_l2_remote_ue of this ProSeCapability.


        :param prose_l2_remote_ue: The prose_l2_remote_ue of this ProSeCapability.
        :type prose_l2_remote_ue: bool
        """

        self._prose_l2_remote_ue = prose_l2_remote_ue

    @property
    def prose_l3_remote_ue(self):
        """Gets the prose_l3_remote_ue of this ProSeCapability.


        :return: The prose_l3_remote_ue of this ProSeCapability.
        :rtype: bool
        """
        return self._prose_l3_remote_ue

    @prose_l3_remote_ue.setter
    def prose_l3_remote_ue(self, prose_l3_remote_ue):
        """Sets the prose_l3_remote_ue of this ProSeCapability.


        :param prose_l3_remote_ue: The prose_l3_remote_ue of this ProSeCapability.
        :type prose_l3_remote_ue: bool
        """

        self._prose_l3_remote_ue = prose_l3_remote_ue
