# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.plmn_id import PlmnId
import re
from openapi_server import util

from openapi_server.models.plmn_id import PlmnId  # noqa: E501
import re  # noqa: E501

class Tmgi(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, mbs_service_id=None, plmn_id=None):  # noqa: E501
        """Tmgi - a model defined in OpenAPI

        :param mbs_service_id: The mbs_service_id of this Tmgi.  # noqa: E501
        :type mbs_service_id: str
        :param plmn_id: The plmn_id of this Tmgi.  # noqa: E501
        :type plmn_id: PlmnId
        """
        self.openapi_types = {
            'mbs_service_id': str,
            'plmn_id': PlmnId
        }

        self.attribute_map = {
            'mbs_service_id': 'mbsServiceId',
            'plmn_id': 'plmnId'
        }

        self._mbs_service_id = mbs_service_id
        self._plmn_id = plmn_id

    @classmethod
    def from_dict(cls, dikt) -> 'Tmgi':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Tmgi of this Tmgi.  # noqa: E501
        :rtype: Tmgi
        """
        return util.deserialize_model(dikt, cls)

    @property
    def mbs_service_id(self):
        """Gets the mbs_service_id of this Tmgi.

        MBS Service ID  # noqa: E501

        :return: The mbs_service_id of this Tmgi.
        :rtype: str
        """
        return self._mbs_service_id

    @mbs_service_id.setter
    def mbs_service_id(self, mbs_service_id):
        """Sets the mbs_service_id of this Tmgi.

        MBS Service ID  # noqa: E501

        :param mbs_service_id: The mbs_service_id of this Tmgi.
        :type mbs_service_id: str
        """
        if mbs_service_id is None:
            raise ValueError("Invalid value for `mbs_service_id`, must not be `None`")  # noqa: E501
        if mbs_service_id is not None and not re.search(r'^[A-Fa-f0-9]{6}$', mbs_service_id):  # noqa: E501
            raise ValueError("Invalid value for `mbs_service_id`, must be a follow pattern or equal to `/^[A-Fa-f0-9]{6}$/`")  # noqa: E501

        self._mbs_service_id = mbs_service_id

    @property
    def plmn_id(self):
        """Gets the plmn_id of this Tmgi.


        :return: The plmn_id of this Tmgi.
        :rtype: PlmnId
        """
        return self._plmn_id

    @plmn_id.setter
    def plmn_id(self, plmn_id):
        """Sets the plmn_id of this Tmgi.


        :param plmn_id: The plmn_id of this Tmgi.
        :type plmn_id: PlmnId
        """
        if plmn_id is None:
            raise ValueError("Invalid value for `plmn_id`, must not be `None`")  # noqa: E501

        self._plmn_id = plmn_id
