# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.identity_range import IdentityRange
from openapi_server.models.internal_group_id_range import InternalGroupIdRange
from openapi_server.models.suci_info import SuciInfo
from openapi_server.models.supi_range import SupiRange
from openapi_server import util

from openapi_server.models.identity_range import IdentityRange  # noqa: E501
from openapi_server.models.internal_group_id_range import InternalGroupIdRange  # noqa: E501
from openapi_server.models.suci_info import SuciInfo  # noqa: E501
from openapi_server.models.supi_range import SupiRange  # noqa: E501

class UdmInfo(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, group_id=None, supi_ranges=None, gpsi_ranges=None, external_group_identifiers_ranges=None, routing_indicators=None, internal_group_identifiers_ranges=None, suci_infos=None):  # noqa: E501
        """UdmInfo - a model defined in OpenAPI

        :param group_id: The group_id of this UdmInfo.  # noqa: E501
        :type group_id: str
        :param supi_ranges: The supi_ranges of this UdmInfo.  # noqa: E501
        :type supi_ranges: List[SupiRange]
        :param gpsi_ranges: The gpsi_ranges of this UdmInfo.  # noqa: E501
        :type gpsi_ranges: List[IdentityRange]
        :param external_group_identifiers_ranges: The external_group_identifiers_ranges of this UdmInfo.  # noqa: E501
        :type external_group_identifiers_ranges: List[IdentityRange]
        :param routing_indicators: The routing_indicators of this UdmInfo.  # noqa: E501
        :type routing_indicators: List[str]
        :param internal_group_identifiers_ranges: The internal_group_identifiers_ranges of this UdmInfo.  # noqa: E501
        :type internal_group_identifiers_ranges: List[InternalGroupIdRange]
        :param suci_infos: The suci_infos of this UdmInfo.  # noqa: E501
        :type suci_infos: List[SuciInfo]
        """
        self.openapi_types = {
            'group_id': str,
            'supi_ranges': List[SupiRange],
            'gpsi_ranges': List[IdentityRange],
            'external_group_identifiers_ranges': List[IdentityRange],
            'routing_indicators': List[str],
            'internal_group_identifiers_ranges': List[InternalGroupIdRange],
            'suci_infos': List[SuciInfo]
        }

        self.attribute_map = {
            'group_id': 'groupId',
            'supi_ranges': 'supiRanges',
            'gpsi_ranges': 'gpsiRanges',
            'external_group_identifiers_ranges': 'externalGroupIdentifiersRanges',
            'routing_indicators': 'routingIndicators',
            'internal_group_identifiers_ranges': 'internalGroupIdentifiersRanges',
            'suci_infos': 'suciInfos'
        }

        self._group_id = group_id
        self._supi_ranges = supi_ranges
        self._gpsi_ranges = gpsi_ranges
        self._external_group_identifiers_ranges = external_group_identifiers_ranges
        self._routing_indicators = routing_indicators
        self._internal_group_identifiers_ranges = internal_group_identifiers_ranges
        self._suci_infos = suci_infos

    @classmethod
    def from_dict(cls, dikt) -> 'UdmInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The UdmInfo of this UdmInfo.  # noqa: E501
        :rtype: UdmInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def group_id(self):
        """Gets the group_id of this UdmInfo.

        Identifier of a group of NFs.  # noqa: E501

        :return: The group_id of this UdmInfo.
        :rtype: str
        """
        return self._group_id

    @group_id.setter
    def group_id(self, group_id):
        """Sets the group_id of this UdmInfo.

        Identifier of a group of NFs.  # noqa: E501

        :param group_id: The group_id of this UdmInfo.
        :type group_id: str
        """

        self._group_id = group_id

    @property
    def supi_ranges(self):
        """Gets the supi_ranges of this UdmInfo.


        :return: The supi_ranges of this UdmInfo.
        :rtype: List[SupiRange]
        """
        return self._supi_ranges

    @supi_ranges.setter
    def supi_ranges(self, supi_ranges):
        """Sets the supi_ranges of this UdmInfo.


        :param supi_ranges: The supi_ranges of this UdmInfo.
        :type supi_ranges: List[SupiRange]
        """
        if supi_ranges is not None and len(supi_ranges) < 1:
            raise ValueError("Invalid value for `supi_ranges`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._supi_ranges = supi_ranges

    @property
    def gpsi_ranges(self):
        """Gets the gpsi_ranges of this UdmInfo.


        :return: The gpsi_ranges of this UdmInfo.
        :rtype: List[IdentityRange]
        """
        return self._gpsi_ranges

    @gpsi_ranges.setter
    def gpsi_ranges(self, gpsi_ranges):
        """Sets the gpsi_ranges of this UdmInfo.


        :param gpsi_ranges: The gpsi_ranges of this UdmInfo.
        :type gpsi_ranges: List[IdentityRange]
        """
        if gpsi_ranges is not None and len(gpsi_ranges) < 1:
            raise ValueError("Invalid value for `gpsi_ranges`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._gpsi_ranges = gpsi_ranges

    @property
    def external_group_identifiers_ranges(self):
        """Gets the external_group_identifiers_ranges of this UdmInfo.


        :return: The external_group_identifiers_ranges of this UdmInfo.
        :rtype: List[IdentityRange]
        """
        return self._external_group_identifiers_ranges

    @external_group_identifiers_ranges.setter
    def external_group_identifiers_ranges(self, external_group_identifiers_ranges):
        """Sets the external_group_identifiers_ranges of this UdmInfo.


        :param external_group_identifiers_ranges: The external_group_identifiers_ranges of this UdmInfo.
        :type external_group_identifiers_ranges: List[IdentityRange]
        """
        if external_group_identifiers_ranges is not None and len(external_group_identifiers_ranges) < 1:
            raise ValueError("Invalid value for `external_group_identifiers_ranges`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._external_group_identifiers_ranges = external_group_identifiers_ranges

    @property
    def routing_indicators(self):
        """Gets the routing_indicators of this UdmInfo.


        :return: The routing_indicators of this UdmInfo.
        :rtype: List[str]
        """
        return self._routing_indicators

    @routing_indicators.setter
    def routing_indicators(self, routing_indicators):
        """Sets the routing_indicators of this UdmInfo.


        :param routing_indicators: The routing_indicators of this UdmInfo.
        :type routing_indicators: List[str]
        """
        if routing_indicators is not None and len(routing_indicators) < 1:
            raise ValueError("Invalid value for `routing_indicators`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._routing_indicators = routing_indicators

    @property
    def internal_group_identifiers_ranges(self):
        """Gets the internal_group_identifiers_ranges of this UdmInfo.


        :return: The internal_group_identifiers_ranges of this UdmInfo.
        :rtype: List[InternalGroupIdRange]
        """
        return self._internal_group_identifiers_ranges

    @internal_group_identifiers_ranges.setter
    def internal_group_identifiers_ranges(self, internal_group_identifiers_ranges):
        """Sets the internal_group_identifiers_ranges of this UdmInfo.


        :param internal_group_identifiers_ranges: The internal_group_identifiers_ranges of this UdmInfo.
        :type internal_group_identifiers_ranges: List[InternalGroupIdRange]
        """
        if internal_group_identifiers_ranges is not None and len(internal_group_identifiers_ranges) < 1:
            raise ValueError("Invalid value for `internal_group_identifiers_ranges`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._internal_group_identifiers_ranges = internal_group_identifiers_ranges

    @property
    def suci_infos(self):
        """Gets the suci_infos of this UdmInfo.


        :return: The suci_infos of this UdmInfo.
        :rtype: List[SuciInfo]
        """
        return self._suci_infos

    @suci_infos.setter
    def suci_infos(self, suci_infos):
        """Sets the suci_infos of this UdmInfo.


        :param suci_infos: The suci_infos of this UdmInfo.
        :type suci_infos: List[SuciInfo]
        """
        if suci_infos is not None and len(suci_infos) < 1:
            raise ValueError("Invalid value for `suci_infos`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._suci_infos = suci_infos
