# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class V2xCapability(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, lte_v2x=False, nr_v2x=False):  # noqa: E501
        """V2xCapability - a model defined in OpenAPI

        :param lte_v2x: The lte_v2x of this V2xCapability.  # noqa: E501
        :type lte_v2x: bool
        :param nr_v2x: The nr_v2x of this V2xCapability.  # noqa: E501
        :type nr_v2x: bool
        """
        self.openapi_types = {
            'lte_v2x': bool,
            'nr_v2x': bool
        }

        self.attribute_map = {
            'lte_v2x': 'lteV2x',
            'nr_v2x': 'nrV2x'
        }

        self._lte_v2x = lte_v2x
        self._nr_v2x = nr_v2x

    @classmethod
    def from_dict(cls, dikt) -> 'V2xCapability':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The V2xCapability of this V2xCapability.  # noqa: E501
        :rtype: V2xCapability
        """
        return util.deserialize_model(dikt, cls)

    @property
    def lte_v2x(self):
        """Gets the lte_v2x of this V2xCapability.


        :return: The lte_v2x of this V2xCapability.
        :rtype: bool
        """
        return self._lte_v2x

    @lte_v2x.setter
    def lte_v2x(self, lte_v2x):
        """Sets the lte_v2x of this V2xCapability.


        :param lte_v2x: The lte_v2x of this V2xCapability.
        :type lte_v2x: bool
        """

        self._lte_v2x = lte_v2x

    @property
    def nr_v2x(self):
        """Gets the nr_v2x of this V2xCapability.


        :return: The nr_v2x of this V2xCapability.
        :rtype: bool
        """
        return self._nr_v2x

    @nr_v2x.setter
    def nr_v2x(self, nr_v2x):
        """Sets the nr_v2x of this V2xCapability.


        :param nr_v2x: The nr_v2x of this V2xCapability.
        :type nr_v2x: bool
        """

        self._nr_v2x = nr_v2x
