version: "3"

services:

  mongo_nwdaf:
    container_name: nwdaf_dvy_mongo_nwdaf
    image: mongo:6.0.2
    expose:
      - "27017"
    restart: unless-stopped
    env_file: ./_env/.env
  
  mongo-express_nwdaf:
    container_name: nwdaf_dvy_mongo_express
    image: mongo-express:1.0.0-alpha.4
    logging:
      driver: 'none'
    restart: unless-stopped
    ports:
      - "8071:8081"
    env_file:
      - ./_env/.env
    depends_on:
      - mongo_nwdaf

  events_subscription:
    container_name: nwdaf_dvy_events_subscription
    build: ./Events_Subscription
    expose:
      - "8080"
    volumes:
      - ./Events_Subscription:/usr/src/app
    extra_hosts:
      - nef_nginx:host-gateway
      - af_listener:host-gateway
    restart: unless-stopped
    env_file: ./_env/.env
    depends_on:
      - mongo_nwdaf
  
  analytics_info:
    container_name: nwdaf_dvy_analytics_info
    build: ./Analytics_Info
    expose:
      - "8080"
    volumes:
      - ./Analytics_Info:/usr/src/app
    restart: unless-stopped
    env_file: ./_env/.env
    depends_on:
      - mongo_nwdaf

  data_management:
    container_name: nwdaf_dvy_data_management
    build: ./Data_Management
    expose:
      - "8080"
    volumes:
      - ./Data_Management:/usr/src/app
    restart: unless-stopped
    env_file: ./_env/.env
    depends_on:
      - mongo_nwdaf

  ml_model_provision:
    container_name: nwdaf_dvy_ml_model_provision
    build: ./ML_Model_Provision
    ports:
      - "8080"
    volumes:
      - ./ML_Model_Provision:/usr/src/app
    restart: unless-stopped
    env_file: ./_env/.env
    depends_on:
      - mongo_nwdaf

  nwdaf_nginx:
    container_name: nwdaf_dvy_nginx
    image: nginx:latest
    ports: 
      - "8070:80"
    volumes:
      - ./nginx:/etc/nginx
    restart: unless-stopped
    environment:
      - NWDAF_HOSTNAME=${NWDAF_HOSTNAME}
    hostname: ${NWDAF_HOSTNAME}
    depends_on:
      - events_subscription
      - data_management
      - ml_model_provision
      - analytics_info

networks:
  default:
    external:
      name: naas-network





  
