# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.plmn_id import PlmnId
from openapi_server import util

from openapi_server.models.plmn_id import PlmnId  # noqa: E501

class PlmnOauth2(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, oauth2_required_plmn_id_list=None, oauth2_not_required_plmn_id_list=None):  # noqa: E501
        """PlmnOauth2 - a model defined in OpenAPI

        :param oauth2_required_plmn_id_list: The oauth2_required_plmn_id_list of this PlmnOauth2.  # noqa: E501
        :type oauth2_required_plmn_id_list: List[PlmnId]
        :param oauth2_not_required_plmn_id_list: The oauth2_not_required_plmn_id_list of this PlmnOauth2.  # noqa: E501
        :type oauth2_not_required_plmn_id_list: List[PlmnId]
        """
        self.openapi_types = {
            'oauth2_required_plmn_id_list': List[PlmnId],
            'oauth2_not_required_plmn_id_list': List[PlmnId]
        }

        self.attribute_map = {
            'oauth2_required_plmn_id_list': 'oauth2RequiredPlmnIdList',
            'oauth2_not_required_plmn_id_list': 'oauth2NotRequiredPlmnIdList'
        }

        self._oauth2_required_plmn_id_list = oauth2_required_plmn_id_list
        self._oauth2_not_required_plmn_id_list = oauth2_not_required_plmn_id_list

    @classmethod
    def from_dict(cls, dikt) -> 'PlmnOauth2':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The PlmnOauth2 of this PlmnOauth2.  # noqa: E501
        :rtype: PlmnOauth2
        """
        return util.deserialize_model(dikt, cls)

    @property
    def oauth2_required_plmn_id_list(self):
        """Gets the oauth2_required_plmn_id_list of this PlmnOauth2.


        :return: The oauth2_required_plmn_id_list of this PlmnOauth2.
        :rtype: List[PlmnId]
        """
        return self._oauth2_required_plmn_id_list

    @oauth2_required_plmn_id_list.setter
    def oauth2_required_plmn_id_list(self, oauth2_required_plmn_id_list):
        """Sets the oauth2_required_plmn_id_list of this PlmnOauth2.


        :param oauth2_required_plmn_id_list: The oauth2_required_plmn_id_list of this PlmnOauth2.
        :type oauth2_required_plmn_id_list: List[PlmnId]
        """
        if oauth2_required_plmn_id_list is not None and len(oauth2_required_plmn_id_list) < 1:
            raise ValueError("Invalid value for `oauth2_required_plmn_id_list`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._oauth2_required_plmn_id_list = oauth2_required_plmn_id_list

    @property
    def oauth2_not_required_plmn_id_list(self):
        """Gets the oauth2_not_required_plmn_id_list of this PlmnOauth2.


        :return: The oauth2_not_required_plmn_id_list of this PlmnOauth2.
        :rtype: List[PlmnId]
        """
        return self._oauth2_not_required_plmn_id_list

    @oauth2_not_required_plmn_id_list.setter
    def oauth2_not_required_plmn_id_list(self, oauth2_not_required_plmn_id_list):
        """Sets the oauth2_not_required_plmn_id_list of this PlmnOauth2.


        :param oauth2_not_required_plmn_id_list: The oauth2_not_required_plmn_id_list of this PlmnOauth2.
        :type oauth2_not_required_plmn_id_list: List[PlmnId]
        """
        if oauth2_not_required_plmn_id_list is not None and len(oauth2_not_required_plmn_id_list) < 1:
            raise ValueError("Invalid value for `oauth2_not_required_plmn_id_list`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._oauth2_not_required_plmn_id_list = oauth2_not_required_plmn_id_list
