# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server.models.ip_addr import IpAddr
from openapi_server import util

from openapi_server.models.ip_addr import IpAddr  # noqa: E501

class Ssm(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, source_ip_addr=None, dest_ip_addr=None):  # noqa: E501
        """Ssm - a model defined in OpenAPI

        :param source_ip_addr: The source_ip_addr of this Ssm.  # noqa: E501
        :type source_ip_addr: IpAddr
        :param dest_ip_addr: The dest_ip_addr of this Ssm.  # noqa: E501
        :type dest_ip_addr: IpAddr
        """
        self.openapi_types = {
            'source_ip_addr': IpAddr,
            'dest_ip_addr': IpAddr
        }

        self.attribute_map = {
            'source_ip_addr': 'sourceIpAddr',
            'dest_ip_addr': 'destIpAddr'
        }

        self._source_ip_addr = source_ip_addr
        self._dest_ip_addr = dest_ip_addr

    @classmethod
    def from_dict(cls, dikt) -> 'Ssm':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Ssm of this Ssm.  # noqa: E501
        :rtype: Ssm
        """
        return util.deserialize_model(dikt, cls)

    @property
    def source_ip_addr(self):
        """Gets the source_ip_addr of this Ssm.


        :return: The source_ip_addr of this Ssm.
        :rtype: IpAddr
        """
        return self._source_ip_addr

    @source_ip_addr.setter
    def source_ip_addr(self, source_ip_addr):
        """Sets the source_ip_addr of this Ssm.


        :param source_ip_addr: The source_ip_addr of this Ssm.
        :type source_ip_addr: IpAddr
        """
        if source_ip_addr is None:
            raise ValueError("Invalid value for `source_ip_addr`, must not be `None`")  # noqa: E501

        self._source_ip_addr = source_ip_addr

    @property
    def dest_ip_addr(self):
        """Gets the dest_ip_addr of this Ssm.


        :return: The dest_ip_addr of this Ssm.
        :rtype: IpAddr
        """
        return self._dest_ip_addr

    @dest_ip_addr.setter
    def dest_ip_addr(self, dest_ip_addr):
        """Sets the dest_ip_addr of this Ssm.


        :param dest_ip_addr: The dest_ip_addr of this Ssm.
        :type dest_ip_addr: IpAddr
        """
        if dest_ip_addr is None:
            raise ValueError("Invalid value for `dest_ip_addr`, must not be `None`")  # noqa: E501

        self._dest_ip_addr = dest_ip_addr
